-- ==========================================================
-- 1. DATA MASKING
-- ==========================================================
CREATE OR REPLACE MASKING POLICY MASK_BORROWER
AS (val STRING) 
RETURNS STRING ->
    CASE
        WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN', 'DATA_ENGINEER') THEN val
        ELSE '*****MASKED*****'
    END;

ALTER TABLE DIM_BORROWER 
MODIFY COLUMN BORROWER 
SET MASKING POLICY MASK_BORROWER;

CREATE OR REPLACE MASKING POLICY MASK_AMOUNT
AS (val FLOAT)
RETURNS FLOAT ->
    CASE
        WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN', 'FINANCE_ROLE') THEN val
        ELSE NULL
    END;

ALTER TABLE FACT_LOANS MODIFY COLUMN ORIGINAL_PRINCIPAL_AMOUNT SET MASKING POLICY MASK_AMOUNT;
ALTER TABLE FACT_LOANS MODIFY COLUMN DISBURSED_AMOUNT SET MASKING POLICY MASK_AMOUNT;
ALTER TABLE FACT_LOANS MODIFY COLUMN REPAID_TO_IBRD SET MASKING POLICY MASK_AMOUNT;

-- ==========================================================
-- 2. RBAC
-- ==========================================================

CREATE ROLE DATA_ENGINEER;
CREATE ROLE ANALYST;
CREATE ROLE FINANCE_ROLE;

GRANT USAGE ON WAREHOUSE LOAN_WH TO ROLE DATA_ENGINEER;
GRANT USAGE ON WAREHOUSE LOAN_WH TO ROLE ANALYST;
GRANT USAGE ON WAREHOUSE LOAN_WH TO ROLE FINANCE_ROLE;

GRANT USAGE ON DATABASE LOAN_DB TO ROLE DATA_ENGINEER;
GRANT USAGE ON DATABASE LOAN_DB TO ROLE ANALYST;

GRANT USAGE ON SCHEMA PUBLIC TO ROLE DATA_ENGINEER;
GRANT USAGE ON SCHEMA PUBLIC TO ROLE ANALYST;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA PUBLIC TO ROLE DATA_ENGINEER;
GRANT SELECT ON ALL TABLES IN SCHEMA PUBLIC TO ROLE ANALYST;
GRANT SELECT ON FACT_LOANS TO ROLE FINANCE_ROLE;
GRANT SELECT ON DIM_BORROWER TO ROLE FINANCE_ROLE;
GRANT ROLE ANALYST TO USER naveen;
GRANT ROLE DATA_ENGINEER TO USER naveen;

-- ==========================================================
-- 3. ROW LEVEL SECURITY
-- ==========================================================
CREATE OR REPLACE ROW ACCESS POLICY REGION_POLICY
AS (region STRING) RETURNS BOOLEAN ->
    CASE
        WHEN CURRENT_ROLE() = 'ANALYST' THEN region = 'ASIA'
        ELSE TRUE
    END;

ALTER TABLE DIM_COUNTRY
ADD ROW ACCESS POLICY REGION_POLICY ON (REGION);

-- ==========================================================
-- 4. DATA REPLICATION
-- ==========================================================
--ALTER DATABASE LOAN_DB SET REPLICATION = ENABLED;
--CREATE DATABASE LOAN_DB_REPLICA FROM REPLICATION OF LOAN_DB;